version: "3"

services:

  mysql:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: ${RESTART}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PSWD}
    networks:
      - network
    volumes:
      - ./config/mysql/mysql.cnf:/etc/mysql/mysql.cnf
      - ./db:/docker-entrypoint-initdb.d/

  web:
    image: dev-php-5.3-web
    container_name: ${COMPOSE_PROJECT_NAME}_web
    build:
      context: ./images/web
      args:
        SSH_PSWD: ${SSH_PSWD}
    depends_on:
      - mysql
    tty: true
    restart: ${RESTART}
    networks:
      - network
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/apache/apache2.conf:/etc/apache2/apache2.conf

networks:

  network:
    external:
      name: ${NETWORK}
